# This file is part of Adblock Plus <https://adblockplus.org/>,
# Copyright (C) 2006-present eyeo GmbH
#
# Adblock Plus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Adblock Plus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
#
# NOTE:
# This CI configuration is meant to be run on private runners, which can be
# provisioned with the Ansible roles from
# https://gitlab.com/eyeo/devops/ansible-role-adblockplus-builder and
# https://gitlab.com/eyeo/devops/ansible-role-gitlab-runner

stages:
  - prepare
  - build
  - test

.dependencies:
  script: &dependencies
    - mkdir -p .git/info
    - pip install --user Jinja2 cryptography
    - python ensure_dependencies.py
    - "[ -d node_modules ] || npm install"

.pull_cache:
  cache:
    key: cache_$CI_COMMIT_SHA
    paths:
      - ./
    policy: pull

.test_template:
  extends: .pull_cache
  stage: test
  before_script: *dependencies

.build:
  extends: .pull_cache
  before_script: *dependencies
  stage: build
  only:
    - master
  script:
    - python build.py build -t $PLATFORM
  artifacts:
    paths:
      - adblockplusfirefox-*.xpi
      - adblockpluschrome-*.zip
      - adblockplusedge-*.appx

lint:
  extends: .test_template
  script:
    - npm run lint

build:chrome:
  extends: .build
  variables:
    PLATFORM: chrome

build:gecko:
  extends: .build
  variables:
    PLATFORM: gecko

build:edge:
  extends: .build
  variables:
    PLATFORM: edge

prepare-dependencies:
  stage: prepare
  script: *dependencies
  cache:
    key: cache_$CI_COMMIT_SHA
    paths:
      - ./
    policy: push

test:gecko:
  extends: .test_template
  script:
    - npm run test-only -- -g gecko

test:chrome:
  extends: .test_template
  script:
    - xvfb-run npm run test-only -- -g chrome
